apiVersion: ingress.astarte-platform.org/v2alpha1
kind: AstarteDefaultIngress
metadata:
  name: adi
spec:
  ### Astarte Default Ingress CRD
  astarte: astarte
  tlsSecret: test-certificate
  api:
    cors: true
    deploy: true
    exposeHousekeeping: true
    tlsSecret: test-certificate
  dashboard:
    deploy: false
  broker:
    deploy: false
